//go:build ignore

// Command genkinds regenerates kinds_generated.go: for every typed syntax
// node kind in the vendored typescript-go `ast` package it emits an IsXxx
// predicate, an AsXxx downcast, and a thin `Xxx struct{ Node }` wrapper in the
// tsmorph package.
//
// Run from the repository root:
//
//	go run ./tools/genkinds
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// alreadyWrapped are the wrapper types already declared by hand in the
// tsmorph package (declarations.go / expr.go). The generator skips them.
var alreadyWrapped = map[string]bool{
	"ClassDeclaration":         true,
	"InterfaceDeclaration":     true,
	"FunctionDeclaration":      true,
	"MethodDeclaration":        true,
	"PropertyDeclaration":      true,
	"EnumDeclaration":          true,
	"TypeAliasDeclaration":     true,
	"VariableStatement":        true,
	"ImportDeclaration":        true,
	"ExportDeclaration":        true,
	"ConstructorDeclaration":   true,
	"ParameterDeclaration":     true,
	"EnumMember":               true,
	"VariableDeclaration":      true,
	"CallExpression":           true,
	"PropertyAccessExpression": true,
	"Identifier":               true,
	"StringLiteral":            true,
	"ArrowFunction":            true,
	"Block":                    true,
	"JsxAttribute":             true,
	"JsxElement":               true,
	"JsxText":                  true,
}

// excluded are abstract, synthetic, or internal kinds that are not intended to
// be surfaced as first-class wrapper types.
var excluded = map[string]bool{
	"CaseOrDefaultClause":          true,
	"BindingPattern":               true,
	"Mutable":                      true,
	"Node":                         true,
	"SourceFile":                   true,
	"SyntaxList":                   true,
	"Token":                        true,
	"FlowReduceLabelData":          true,
	"FlowSwitchClauseData":         true,
	"MissingDeclaration":           true,
	"NotEmittedStatement":          true,
	"NotEmittedTypeElement":        true,
	"SyntheticExpression":          true,
	"SyntheticReferenceExpression": true,
	"PartiallyEmittedExpression":   true,
	"OmittedExpression":            true,
	"SemicolonClassElement":        true,
	"KeywordExpression":            true,
	"KeywordTypeNode":              true,
	"JSDocParameterOrPropertyTag":  true,
}

func main() {
	astDir := filepath.Join("third_party", "typescript-go", "ts", "ast")
	outPath := "kinds_generated.go"
	if len(os.Args) > 2 {
		astDir = os.Args[1]
		outPath = os.Args[2]
	}

	asNames := map[string]string{} // AsName -> struct name (e.g. "IfStatement" -> "IfStatement")
	isNames := map[string]bool{}

	fset := token.NewFileSet()
	entries, err := os.ReadDir(astDir)
	if err != nil {
		fatalf("%v", err)
	}
	for _, e := range entries {
		if e.IsDir() || strings.HasSuffix(e.Name(), "_test.go") {
			continue
		}
		path := filepath.Join(astDir, e.Name())
		f, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			fatalf("parse %s: %v", path, err)
		}
		for _, decl := range f.Decls {
			fd, ok := decl.(*ast.FuncDecl)
			if !ok || fd.Name == nil {
				continue
			}
			if isAsMethod(fd) {
				asNames[fd.Name.Name[2:]] = resultStructName(fd)
			} else if isIsFunc(fd) {
				isNames[fd.Name.Name] = true
			}
		}
	}

	var names []string
	for name := range asNames {
		if alreadyWrapped[name] || excluded[name] {
			continue
		}
		if !isNames["Is"+name] {
			fmt.Fprintf(os.Stderr, "genkinds: warning: no Is%s predicate for As%s; skipping\n", name, name)
			continue
		}
		names = append(names, name)
	}
	sort.Strings(names)

	var b bytes.Buffer
	b.WriteString("// Code generated by tools/genkinds; DO NOT EDIT.\n\n")
	b.WriteString("package tsmorph\n\n")
	b.WriteString("import \"github.com/jclyons52/ts-go-morph/third_party/typescript-go/ts/ast\"\n\n")

	for _, name := range names {
		embed := "Node"
		if strings.HasPrefix(name, "JSDoc") && strings.HasSuffix(name, "Tag") {
			embed = "JSDocTag"
		}
		literal := "Node: n"
		if embed != "Node" {
			literal = embed + ": " + embed + "{Node: n}"
		}
		fmt.Fprintf(&b, "// %s wraps a %s node.\n", name, name)
		fmt.Fprintf(&b, "type %s struct{ %s }\n\n", name, embed)
		fmt.Fprintf(&b, "// Is%s reports whether the node is a %s.\n", name, name)
		fmt.Fprintf(&b, "func (n Node) Is%s() bool { return ast.Is%s(n.node) }\n\n", name, name)
		fmt.Fprintf(&b, "// As%s downcasts the node, or returns false.\n", name)
		fmt.Fprintf(&b, "func (n Node) As%s() (%s, bool) {\n", name, name)
		fmt.Fprintf(&b, "\tn.check()\n")
		fmt.Fprintf(&b, "\tif !n.Is%s() {\n\t\treturn %s{}, false\n\t}\n", name, name)
		fmt.Fprintf(&b, "\treturn %s{%s}, true\n}\n\n", name, literal)
	}

	src, err := format.Source(b.Bytes())
	if err != nil {
		fatalf("format generated code: %v", err)
	}
	if err := os.WriteFile(outPath, src, 0o644); err != nil {
		fatalf("write %s: %v", outPath, err)
	}
	fmt.Printf("wrote %s (%d kinds)\n", outPath, len(names))
}

func isAsMethod(fd *ast.FuncDecl) bool {
	if fd.Recv == nil || len(fd.Recv.List) != 1 || len(fd.Name.Name) < 3 || !strings.HasPrefix(fd.Name.Name, "As") {
		return false
	}
	if fd.Type.Results == nil || len(fd.Type.Results.List) != 1 {
		return false
	}
	se, ok := fd.Type.Results.List[0].Type.(*ast.StarExpr)
	if !ok {
		return false
	}
	if _, ok := se.X.(*ast.Ident); !ok {
		return false
	}
	// Recv must be *Node.
	se2, ok := fd.Recv.List[0].Type.(*ast.StarExpr)
	if !ok {
		return false
	}
	id, ok := se2.X.(*ast.Ident)
	return ok && id.Name == "Node"
}

func resultStructName(fd *ast.FuncDecl) string {
	se := fd.Type.Results.List[0].Type.(*ast.StarExpr)
	return se.X.(*ast.Ident).Name
}

func isIsFunc(fd *ast.FuncDecl) bool {
	if fd.Recv != nil || !strings.HasPrefix(fd.Name.Name, "Is") {
		return false
	}
	if fd.Type.Params == nil || len(fd.Type.Params.List) != 1 {
		return false
	}
	se, ok := fd.Type.Params.List[0].Type.(*ast.StarExpr)
	if !ok {
		return false
	}
	id, ok := se.X.(*ast.Ident)
	if !ok || id.Name != "Node" {
		return false
	}
	return fd.Type.Results != nil && len(fd.Type.Results.List) == 1
}

func fatalf(format string, args ...interface{}) {
	fmt.Fprintf(os.Stderr, "genkinds: "+format+"\n", args...)
	os.Exit(1)
}
