// Code generated by tools/genkinds; DO NOT EDIT.

package tsmorph

import "github.com/jclyons52/ts-go-morph/third_party/typescript-go/ts/ast"

// ArrayLiteralExpression wraps a ArrayLiteralExpression node.
type ArrayLiteralExpression struct{ Node }

// IsArrayLiteralExpression reports whether the node is a ArrayLiteralExpression.
func (n Node) IsArrayLiteralExpression() bool { return ast.IsArrayLiteralExpression(n.node) }

// AsArrayLiteralExpression downcasts the node, or returns false.
func (n Node) AsArrayLiteralExpression() (ArrayLiteralExpression, bool) {
	n.check()
	if !n.IsArrayLiteralExpression() {
		return ArrayLiteralExpression{}, false
	}
	return ArrayLiteralExpression{Node: n}, true
}

// ArrayTypeNode wraps a ArrayTypeNode node.
type ArrayTypeNode struct{ Node }

// IsArrayTypeNode reports whether the node is a ArrayTypeNode.
func (n Node) IsArrayTypeNode() bool { return ast.IsArrayTypeNode(n.node) }

// AsArrayTypeNode downcasts the node, or returns false.
func (n Node) AsArrayTypeNode() (ArrayTypeNode, bool) {
	n.check()
	if !n.IsArrayTypeNode() {
		return ArrayTypeNode{}, false
	}
	return ArrayTypeNode{Node: n}, true
}

// AsExpression wraps a AsExpression node.
type AsExpression struct{ Node }

// IsAsExpression reports whether the node is a AsExpression.
func (n Node) IsAsExpression() bool { return ast.IsAsExpression(n.node) }

// AsAsExpression downcasts the node, or returns false.
func (n Node) AsAsExpression() (AsExpression, bool) {
	n.check()
	if !n.IsAsExpression() {
		return AsExpression{}, false
	}
	return AsExpression{Node: n}, true
}

// AwaitExpression wraps a AwaitExpression node.
type AwaitExpression struct{ Node }

// IsAwaitExpression reports whether the node is a AwaitExpression.
func (n Node) IsAwaitExpression() bool { return ast.IsAwaitExpression(n.node) }

// AsAwaitExpression downcasts the node, or returns false.
func (n Node) AsAwaitExpression() (AwaitExpression, bool) {
	n.check()
	if !n.IsAwaitExpression() {
		return AwaitExpression{}, false
	}
	return AwaitExpression{Node: n}, true
}

// BigIntLiteral wraps a BigIntLiteral node.
type BigIntLiteral struct{ Node }

// IsBigIntLiteral reports whether the node is a BigIntLiteral.
func (n Node) IsBigIntLiteral() bool { return ast.IsBigIntLiteral(n.node) }

// AsBigIntLiteral downcasts the node, or returns false.
func (n Node) AsBigIntLiteral() (BigIntLiteral, bool) {
	n.check()
	if !n.IsBigIntLiteral() {
		return BigIntLiteral{}, false
	}
	return BigIntLiteral{Node: n}, true
}

// BinaryExpression wraps a BinaryExpression node.
type BinaryExpression struct{ Node }

// IsBinaryExpression reports whether the node is a BinaryExpression.
func (n Node) IsBinaryExpression() bool { return ast.IsBinaryExpression(n.node) }

// AsBinaryExpression downcasts the node, or returns false.
func (n Node) AsBinaryExpression() (BinaryExpression, bool) {
	n.check()
	if !n.IsBinaryExpression() {
		return BinaryExpression{}, false
	}
	return BinaryExpression{Node: n}, true
}

// BindingElement wraps a BindingElement node.
type BindingElement struct{ Node }

// IsBindingElement reports whether the node is a BindingElement.
func (n Node) IsBindingElement() bool { return ast.IsBindingElement(n.node) }

// AsBindingElement downcasts the node, or returns false.
func (n Node) AsBindingElement() (BindingElement, bool) {
	n.check()
	if !n.IsBindingElement() {
		return BindingElement{}, false
	}
	return BindingElement{Node: n}, true
}

// BreakStatement wraps a BreakStatement node.
type BreakStatement struct{ Node }

// IsBreakStatement reports whether the node is a BreakStatement.
func (n Node) IsBreakStatement() bool { return ast.IsBreakStatement(n.node) }

// AsBreakStatement downcasts the node, or returns false.
func (n Node) AsBreakStatement() (BreakStatement, bool) {
	n.check()
	if !n.IsBreakStatement() {
		return BreakStatement{}, false
	}
	return BreakStatement{Node: n}, true
}

// CallSignatureDeclaration wraps a CallSignatureDeclaration node.
type CallSignatureDeclaration struct{ Node }

// IsCallSignatureDeclaration reports whether the node is a CallSignatureDeclaration.
func (n Node) IsCallSignatureDeclaration() bool { return ast.IsCallSignatureDeclaration(n.node) }

// AsCallSignatureDeclaration downcasts the node, or returns false.
func (n Node) AsCallSignatureDeclaration() (CallSignatureDeclaration, bool) {
	n.check()
	if !n.IsCallSignatureDeclaration() {
		return CallSignatureDeclaration{}, false
	}
	return CallSignatureDeclaration{Node: n}, true
}

// CaseBlock wraps a CaseBlock node.
type CaseBlock struct{ Node }

// IsCaseBlock reports whether the node is a CaseBlock.
func (n Node) IsCaseBlock() bool { return ast.IsCaseBlock(n.node) }

// AsCaseBlock downcasts the node, or returns false.
func (n Node) AsCaseBlock() (CaseBlock, bool) {
	n.check()
	if !n.IsCaseBlock() {
		return CaseBlock{}, false
	}
	return CaseBlock{Node: n}, true
}

// CatchClause wraps a CatchClause node.
type CatchClause struct{ Node }

// IsCatchClause reports whether the node is a CatchClause.
func (n Node) IsCatchClause() bool { return ast.IsCatchClause(n.node) }

// AsCatchClause downcasts the node, or returns false.
func (n Node) AsCatchClause() (CatchClause, bool) {
	n.check()
	if !n.IsCatchClause() {
		return CatchClause{}, false
	}
	return CatchClause{Node: n}, true
}

// ClassExpression wraps a ClassExpression node.
type ClassExpression struct{ Node }

// IsClassExpression reports whether the node is a ClassExpression.
func (n Node) IsClassExpression() bool { return ast.IsClassExpression(n.node) }

// AsClassExpression downcasts the node, or returns false.
func (n Node) AsClassExpression() (ClassExpression, bool) {
	n.check()
	if !n.IsClassExpression() {
		return ClassExpression{}, false
	}
	return ClassExpression{Node: n}, true
}

// ClassStaticBlockDeclaration wraps a ClassStaticBlockDeclaration node.
type ClassStaticBlockDeclaration struct{ Node }

// IsClassStaticBlockDeclaration reports whether the node is a ClassStaticBlockDeclaration.
func (n Node) IsClassStaticBlockDeclaration() bool { return ast.IsClassStaticBlockDeclaration(n.node) }

// AsClassStaticBlockDeclaration downcasts the node, or returns false.
func (n Node) AsClassStaticBlockDeclaration() (ClassStaticBlockDeclaration, bool) {
	n.check()
	if !n.IsClassStaticBlockDeclaration() {
		return ClassStaticBlockDeclaration{}, false
	}
	return ClassStaticBlockDeclaration{Node: n}, true
}

// ComputedPropertyName wraps a ComputedPropertyName node.
type ComputedPropertyName struct{ Node }

// IsComputedPropertyName reports whether the node is a ComputedPropertyName.
func (n Node) IsComputedPropertyName() bool { return ast.IsComputedPropertyName(n.node) }

// AsComputedPropertyName downcasts the node, or returns false.
func (n Node) AsComputedPropertyName() (ComputedPropertyName, bool) {
	n.check()
	if !n.IsComputedPropertyName() {
		return ComputedPropertyName{}, false
	}
	return ComputedPropertyName{Node: n}, true
}

// ConditionalExpression wraps a ConditionalExpression node.
type ConditionalExpression struct{ Node }

// IsConditionalExpression reports whether the node is a ConditionalExpression.
func (n Node) IsConditionalExpression() bool { return ast.IsConditionalExpression(n.node) }

// AsConditionalExpression downcasts the node, or returns false.
func (n Node) AsConditionalExpression() (ConditionalExpression, bool) {
	n.check()
	if !n.IsConditionalExpression() {
		return ConditionalExpression{}, false
	}
	return ConditionalExpression{Node: n}, true
}

// ConditionalTypeNode wraps a ConditionalTypeNode node.
type ConditionalTypeNode struct{ Node }

// IsConditionalTypeNode reports whether the node is a ConditionalTypeNode.
func (n Node) IsConditionalTypeNode() bool { return ast.IsConditionalTypeNode(n.node) }

// AsConditionalTypeNode downcasts the node, or returns false.
func (n Node) AsConditionalTypeNode() (ConditionalTypeNode, bool) {
	n.check()
	if !n.IsConditionalTypeNode() {
		return ConditionalTypeNode{}, false
	}
	return ConditionalTypeNode{Node: n}, true
}

// ConstructSignatureDeclaration wraps a ConstructSignatureDeclaration node.
type ConstructSignatureDeclaration struct{ Node }

// IsConstructSignatureDeclaration reports whether the node is a ConstructSignatureDeclaration.
func (n Node) IsConstructSignatureDeclaration() bool {
	return ast.IsConstructSignatureDeclaration(n.node)
}

// AsConstructSignatureDeclaration downcasts the node, or returns false.
func (n Node) AsConstructSignatureDeclaration() (ConstructSignatureDeclaration, bool) {
	n.check()
	if !n.IsConstructSignatureDeclaration() {
		return ConstructSignatureDeclaration{}, false
	}
	return ConstructSignatureDeclaration{Node: n}, true
}

// ConstructorTypeNode wraps a ConstructorTypeNode node.
type ConstructorTypeNode struct{ Node }

// IsConstructorTypeNode reports whether the node is a ConstructorTypeNode.
func (n Node) IsConstructorTypeNode() bool { return ast.IsConstructorTypeNode(n.node) }

// AsConstructorTypeNode downcasts the node, or returns false.
func (n Node) AsConstructorTypeNode() (ConstructorTypeNode, bool) {
	n.check()
	if !n.IsConstructorTypeNode() {
		return ConstructorTypeNode{}, false
	}
	return ConstructorTypeNode{Node: n}, true
}

// ContinueStatement wraps a ContinueStatement node.
type ContinueStatement struct{ Node }

// IsContinueStatement reports whether the node is a ContinueStatement.
func (n Node) IsContinueStatement() bool { return ast.IsContinueStatement(n.node) }

// AsContinueStatement downcasts the node, or returns false.
func (n Node) AsContinueStatement() (ContinueStatement, bool) {
	n.check()
	if !n.IsContinueStatement() {
		return ContinueStatement{}, false
	}
	return ContinueStatement{Node: n}, true
}

// DebuggerStatement wraps a DebuggerStatement node.
type DebuggerStatement struct{ Node }

// IsDebuggerStatement reports whether the node is a DebuggerStatement.
func (n Node) IsDebuggerStatement() bool { return ast.IsDebuggerStatement(n.node) }

// AsDebuggerStatement downcasts the node, or returns false.
func (n Node) AsDebuggerStatement() (DebuggerStatement, bool) {
	n.check()
	if !n.IsDebuggerStatement() {
		return DebuggerStatement{}, false
	}
	return DebuggerStatement{Node: n}, true
}

// Decorator wraps a Decorator node.
type Decorator struct{ Node }

// IsDecorator reports whether the node is a Decorator.
func (n Node) IsDecorator() bool { return ast.IsDecorator(n.node) }

// AsDecorator downcasts the node, or returns false.
func (n Node) AsDecorator() (Decorator, bool) {
	n.check()
	if !n.IsDecorator() {
		return Decorator{}, false
	}
	return Decorator{Node: n}, true
}

// DeleteExpression wraps a DeleteExpression node.
type DeleteExpression struct{ Node }

// IsDeleteExpression reports whether the node is a DeleteExpression.
func (n Node) IsDeleteExpression() bool { return ast.IsDeleteExpression(n.node) }

// AsDeleteExpression downcasts the node, or returns false.
func (n Node) AsDeleteExpression() (DeleteExpression, bool) {
	n.check()
	if !n.IsDeleteExpression() {
		return DeleteExpression{}, false
	}
	return DeleteExpression{Node: n}, true
}

// DoStatement wraps a DoStatement node.
type DoStatement struct{ Node }

// IsDoStatement reports whether the node is a DoStatement.
func (n Node) IsDoStatement() bool { return ast.IsDoStatement(n.node) }

// AsDoStatement downcasts the node, or returns false.
func (n Node) AsDoStatement() (DoStatement, bool) {
	n.check()
	if !n.IsDoStatement() {
		return DoStatement{}, false
	}
	return DoStatement{Node: n}, true
}

// ElementAccessExpression wraps a ElementAccessExpression node.
type ElementAccessExpression struct{ Node }

// IsElementAccessExpression reports whether the node is a ElementAccessExpression.
func (n Node) IsElementAccessExpression() bool { return ast.IsElementAccessExpression(n.node) }

// AsElementAccessExpression downcasts the node, or returns false.
func (n Node) AsElementAccessExpression() (ElementAccessExpression, bool) {
	n.check()
	if !n.IsElementAccessExpression() {
		return ElementAccessExpression{}, false
	}
	return ElementAccessExpression{Node: n}, true
}

// EmptyStatement wraps a EmptyStatement node.
type EmptyStatement struct{ Node }

// IsEmptyStatement reports whether the node is a EmptyStatement.
func (n Node) IsEmptyStatement() bool { return ast.IsEmptyStatement(n.node) }

// AsEmptyStatement downcasts the node, or returns false.
func (n Node) AsEmptyStatement() (EmptyStatement, bool) {
	n.check()
	if !n.IsEmptyStatement() {
		return EmptyStatement{}, false
	}
	return EmptyStatement{Node: n}, true
}

// ExportAssignment wraps a ExportAssignment node.
type ExportAssignment struct{ Node }

// IsExportAssignment reports whether the node is a ExportAssignment.
func (n Node) IsExportAssignment() bool { return ast.IsExportAssignment(n.node) }

// AsExportAssignment downcasts the node, or returns false.
func (n Node) AsExportAssignment() (ExportAssignment, bool) {
	n.check()
	if !n.IsExportAssignment() {
		return ExportAssignment{}, false
	}
	return ExportAssignment{Node: n}, true
}

// ExportSpecifier wraps a ExportSpecifier node.
type ExportSpecifier struct{ Node }

// IsExportSpecifier reports whether the node is a ExportSpecifier.
func (n Node) IsExportSpecifier() bool { return ast.IsExportSpecifier(n.node) }

// AsExportSpecifier downcasts the node, or returns false.
func (n Node) AsExportSpecifier() (ExportSpecifier, bool) {
	n.check()
	if !n.IsExportSpecifier() {
		return ExportSpecifier{}, false
	}
	return ExportSpecifier{Node: n}, true
}

// ExpressionStatement wraps a ExpressionStatement node.
type ExpressionStatement struct{ Node }

// IsExpressionStatement reports whether the node is a ExpressionStatement.
func (n Node) IsExpressionStatement() bool { return ast.IsExpressionStatement(n.node) }

// AsExpressionStatement downcasts the node, or returns false.
func (n Node) AsExpressionStatement() (ExpressionStatement, bool) {
	n.check()
	if !n.IsExpressionStatement() {
		return ExpressionStatement{}, false
	}
	return ExpressionStatement{Node: n}, true
}

// ExpressionWithTypeArguments wraps a ExpressionWithTypeArguments node.
type ExpressionWithTypeArguments struct{ Node }

// IsExpressionWithTypeArguments reports whether the node is a ExpressionWithTypeArguments.
func (n Node) IsExpressionWithTypeArguments() bool { return ast.IsExpressionWithTypeArguments(n.node) }

// AsExpressionWithTypeArguments downcasts the node, or returns false.
func (n Node) AsExpressionWithTypeArguments() (ExpressionWithTypeArguments, bool) {
	n.check()
	if !n.IsExpressionWithTypeArguments() {
		return ExpressionWithTypeArguments{}, false
	}
	return ExpressionWithTypeArguments{Node: n}, true
}

// ExternalModuleReference wraps a ExternalModuleReference node.
type ExternalModuleReference struct{ Node }

// IsExternalModuleReference reports whether the node is a ExternalModuleReference.
func (n Node) IsExternalModuleReference() bool { return ast.IsExternalModuleReference(n.node) }

// AsExternalModuleReference downcasts the node, or returns false.
func (n Node) AsExternalModuleReference() (ExternalModuleReference, bool) {
	n.check()
	if !n.IsExternalModuleReference() {
		return ExternalModuleReference{}, false
	}
	return ExternalModuleReference{Node: n}, true
}

// ForInOrOfStatement wraps a ForInOrOfStatement node.
type ForInOrOfStatement struct{ Node }

// IsForInOrOfStatement reports whether the node is a ForInOrOfStatement.
func (n Node) IsForInOrOfStatement() bool { return ast.IsForInOrOfStatement(n.node) }

// AsForInOrOfStatement downcasts the node, or returns false.
func (n Node) AsForInOrOfStatement() (ForInOrOfStatement, bool) {
	n.check()
	if !n.IsForInOrOfStatement() {
		return ForInOrOfStatement{}, false
	}
	return ForInOrOfStatement{Node: n}, true
}

// ForStatement wraps a ForStatement node.
type ForStatement struct{ Node }

// IsForStatement reports whether the node is a ForStatement.
func (n Node) IsForStatement() bool { return ast.IsForStatement(n.node) }

// AsForStatement downcasts the node, or returns false.
func (n Node) AsForStatement() (ForStatement, bool) {
	n.check()
	if !n.IsForStatement() {
		return ForStatement{}, false
	}
	return ForStatement{Node: n}, true
}

// FunctionExpression wraps a FunctionExpression node.
type FunctionExpression struct{ Node }

// IsFunctionExpression reports whether the node is a FunctionExpression.
func (n Node) IsFunctionExpression() bool { return ast.IsFunctionExpression(n.node) }

// AsFunctionExpression downcasts the node, or returns false.
func (n Node) AsFunctionExpression() (FunctionExpression, bool) {
	n.check()
	if !n.IsFunctionExpression() {
		return FunctionExpression{}, false
	}
	return FunctionExpression{Node: n}, true
}

// FunctionTypeNode wraps a FunctionTypeNode node.
type FunctionTypeNode struct{ Node }

// IsFunctionTypeNode reports whether the node is a FunctionTypeNode.
func (n Node) IsFunctionTypeNode() bool { return ast.IsFunctionTypeNode(n.node) }

// AsFunctionTypeNode downcasts the node, or returns false.
func (n Node) AsFunctionTypeNode() (FunctionTypeNode, bool) {
	n.check()
	if !n.IsFunctionTypeNode() {
		return FunctionTypeNode{}, false
	}
	return FunctionTypeNode{Node: n}, true
}

// GetAccessorDeclaration wraps a GetAccessorDeclaration node.
type GetAccessorDeclaration struct{ Node }

// IsGetAccessorDeclaration reports whether the node is a GetAccessorDeclaration.
func (n Node) IsGetAccessorDeclaration() bool { return ast.IsGetAccessorDeclaration(n.node) }

// AsGetAccessorDeclaration downcasts the node, or returns false.
func (n Node) AsGetAccessorDeclaration() (GetAccessorDeclaration, bool) {
	n.check()
	if !n.IsGetAccessorDeclaration() {
		return GetAccessorDeclaration{}, false
	}
	return GetAccessorDeclaration{Node: n}, true
}

// HeritageClause wraps a HeritageClause node.
type HeritageClause struct{ Node }

// IsHeritageClause reports whether the node is a HeritageClause.
func (n Node) IsHeritageClause() bool { return ast.IsHeritageClause(n.node) }

// AsHeritageClause downcasts the node, or returns false.
func (n Node) AsHeritageClause() (HeritageClause, bool) {
	n.check()
	if !n.IsHeritageClause() {
		return HeritageClause{}, false
	}
	return HeritageClause{Node: n}, true
}

// IfStatement wraps a IfStatement node.
type IfStatement struct{ Node }

// IsIfStatement reports whether the node is a IfStatement.
func (n Node) IsIfStatement() bool { return ast.IsIfStatement(n.node) }

// AsIfStatement downcasts the node, or returns false.
func (n Node) AsIfStatement() (IfStatement, bool) {
	n.check()
	if !n.IsIfStatement() {
		return IfStatement{}, false
	}
	return IfStatement{Node: n}, true
}

// ImportAttribute wraps a ImportAttribute node.
type ImportAttribute struct{ Node }

// IsImportAttribute reports whether the node is a ImportAttribute.
func (n Node) IsImportAttribute() bool { return ast.IsImportAttribute(n.node) }

// AsImportAttribute downcasts the node, or returns false.
func (n Node) AsImportAttribute() (ImportAttribute, bool) {
	n.check()
	if !n.IsImportAttribute() {
		return ImportAttribute{}, false
	}
	return ImportAttribute{Node: n}, true
}

// ImportAttributes wraps a ImportAttributes node.
type ImportAttributes struct{ Node }

// IsImportAttributes reports whether the node is a ImportAttributes.
func (n Node) IsImportAttributes() bool { return ast.IsImportAttributes(n.node) }

// AsImportAttributes downcasts the node, or returns false.
func (n Node) AsImportAttributes() (ImportAttributes, bool) {
	n.check()
	if !n.IsImportAttributes() {
		return ImportAttributes{}, false
	}
	return ImportAttributes{Node: n}, true
}

// ImportClause wraps a ImportClause node.
type ImportClause struct{ Node }

// IsImportClause reports whether the node is a ImportClause.
func (n Node) IsImportClause() bool { return ast.IsImportClause(n.node) }

// AsImportClause downcasts the node, or returns false.
func (n Node) AsImportClause() (ImportClause, bool) {
	n.check()
	if !n.IsImportClause() {
		return ImportClause{}, false
	}
	return ImportClause{Node: n}, true
}

// ImportEqualsDeclaration wraps a ImportEqualsDeclaration node.
type ImportEqualsDeclaration struct{ Node }

// IsImportEqualsDeclaration reports whether the node is a ImportEqualsDeclaration.
func (n Node) IsImportEqualsDeclaration() bool { return ast.IsImportEqualsDeclaration(n.node) }

// AsImportEqualsDeclaration downcasts the node, or returns false.
func (n Node) AsImportEqualsDeclaration() (ImportEqualsDeclaration, bool) {
	n.check()
	if !n.IsImportEqualsDeclaration() {
		return ImportEqualsDeclaration{}, false
	}
	return ImportEqualsDeclaration{Node: n}, true
}

// ImportSpecifier wraps a ImportSpecifier node.
type ImportSpecifier struct{ Node }

// IsImportSpecifier reports whether the node is a ImportSpecifier.
func (n Node) IsImportSpecifier() bool { return ast.IsImportSpecifier(n.node) }

// AsImportSpecifier downcasts the node, or returns false.
func (n Node) AsImportSpecifier() (ImportSpecifier, bool) {
	n.check()
	if !n.IsImportSpecifier() {
		return ImportSpecifier{}, false
	}
	return ImportSpecifier{Node: n}, true
}

// ImportTypeNode wraps a ImportTypeNode node.
type ImportTypeNode struct{ Node }

// IsImportTypeNode reports whether the node is a ImportTypeNode.
func (n Node) IsImportTypeNode() bool { return ast.IsImportTypeNode(n.node) }

// AsImportTypeNode downcasts the node, or returns false.
func (n Node) AsImportTypeNode() (ImportTypeNode, bool) {
	n.check()
	if !n.IsImportTypeNode() {
		return ImportTypeNode{}, false
	}
	return ImportTypeNode{Node: n}, true
}

// IndexSignatureDeclaration wraps a IndexSignatureDeclaration node.
type IndexSignatureDeclaration struct{ Node }

// IsIndexSignatureDeclaration reports whether the node is a IndexSignatureDeclaration.
func (n Node) IsIndexSignatureDeclaration() bool { return ast.IsIndexSignatureDeclaration(n.node) }

// AsIndexSignatureDeclaration downcasts the node, or returns false.
func (n Node) AsIndexSignatureDeclaration() (IndexSignatureDeclaration, bool) {
	n.check()
	if !n.IsIndexSignatureDeclaration() {
		return IndexSignatureDeclaration{}, false
	}
	return IndexSignatureDeclaration{Node: n}, true
}

// IndexedAccessTypeNode wraps a IndexedAccessTypeNode node.
type IndexedAccessTypeNode struct{ Node }

// IsIndexedAccessTypeNode reports whether the node is a IndexedAccessTypeNode.
func (n Node) IsIndexedAccessTypeNode() bool { return ast.IsIndexedAccessTypeNode(n.node) }

// AsIndexedAccessTypeNode downcasts the node, or returns false.
func (n Node) AsIndexedAccessTypeNode() (IndexedAccessTypeNode, bool) {
	n.check()
	if !n.IsIndexedAccessTypeNode() {
		return IndexedAccessTypeNode{}, false
	}
	return IndexedAccessTypeNode{Node: n}, true
}

// InferTypeNode wraps a InferTypeNode node.
type InferTypeNode struct{ Node }

// IsInferTypeNode reports whether the node is a InferTypeNode.
func (n Node) IsInferTypeNode() bool { return ast.IsInferTypeNode(n.node) }

// AsInferTypeNode downcasts the node, or returns false.
func (n Node) AsInferTypeNode() (InferTypeNode, bool) {
	n.check()
	if !n.IsInferTypeNode() {
		return InferTypeNode{}, false
	}
	return InferTypeNode{Node: n}, true
}

// IntersectionTypeNode wraps a IntersectionTypeNode node.
type IntersectionTypeNode struct{ Node }

// IsIntersectionTypeNode reports whether the node is a IntersectionTypeNode.
func (n Node) IsIntersectionTypeNode() bool { return ast.IsIntersectionTypeNode(n.node) }

// AsIntersectionTypeNode downcasts the node, or returns false.
func (n Node) AsIntersectionTypeNode() (IntersectionTypeNode, bool) {
	n.check()
	if !n.IsIntersectionTypeNode() {
		return IntersectionTypeNode{}, false
	}
	return IntersectionTypeNode{Node: n}, true
}

// JSDoc wraps a JSDoc node.
type JSDoc struct{ Node }

// IsJSDoc reports whether the node is a JSDoc.
func (n Node) IsJSDoc() bool { return ast.IsJSDoc(n.node) }

// AsJSDoc downcasts the node, or returns false.
func (n Node) AsJSDoc() (JSDoc, bool) {
	n.check()
	if !n.IsJSDoc() {
		return JSDoc{}, false
	}
	return JSDoc{Node: n}, true
}

// JSDocAllType wraps a JSDocAllType node.
type JSDocAllType struct{ Node }

// IsJSDocAllType reports whether the node is a JSDocAllType.
func (n Node) IsJSDocAllType() bool { return ast.IsJSDocAllType(n.node) }

// AsJSDocAllType downcasts the node, or returns false.
func (n Node) AsJSDocAllType() (JSDocAllType, bool) {
	n.check()
	if !n.IsJSDocAllType() {
		return JSDocAllType{}, false
	}
	return JSDocAllType{Node: n}, true
}

// JSDocAugmentsTag wraps a JSDocAugmentsTag node.
type JSDocAugmentsTag struct{ JSDocTag }

// IsJSDocAugmentsTag reports whether the node is a JSDocAugmentsTag.
func (n Node) IsJSDocAugmentsTag() bool { return ast.IsJSDocAugmentsTag(n.node) }

// AsJSDocAugmentsTag downcasts the node, or returns false.
func (n Node) AsJSDocAugmentsTag() (JSDocAugmentsTag, bool) {
	n.check()
	if !n.IsJSDocAugmentsTag() {
		return JSDocAugmentsTag{}, false
	}
	return JSDocAugmentsTag{JSDocTag: JSDocTag{Node: n}}, true
}

// JSDocCallbackTag wraps a JSDocCallbackTag node.
type JSDocCallbackTag struct{ JSDocTag }

// IsJSDocCallbackTag reports whether the node is a JSDocCallbackTag.
func (n Node) IsJSDocCallbackTag() bool { return ast.IsJSDocCallbackTag(n.node) }

// AsJSDocCallbackTag downcasts the node, or returns false.
func (n Node) AsJSDocCallbackTag() (JSDocCallbackTag, bool) {
	n.check()
	if !n.IsJSDocCallbackTag() {
		return JSDocCallbackTag{}, false
	}
	return JSDocCallbackTag{JSDocTag: JSDocTag{Node: n}}, true
}

// JSDocDeprecatedTag wraps a JSDocDeprecatedTag node.
type JSDocDeprecatedTag struct{ JSDocTag }

// IsJSDocDeprecatedTag reports whether the node is a JSDocDeprecatedTag.
func (n Node) IsJSDocDeprecatedTag() bool { return ast.IsJSDocDeprecatedTag(n.node) }

// AsJSDocDeprecatedTag downcasts the node, or returns false.
func (n Node) AsJSDocDeprecatedTag() (JSDocDeprecatedTag, bool) {
	n.check()
	if !n.IsJSDocDeprecatedTag() {
		return JSDocDeprecatedTag{}, false
	}
	return JSDocDeprecatedTag{JSDocTag: JSDocTag{Node: n}}, true
}

// JSDocImplementsTag wraps a JSDocImplementsTag node.
type JSDocImplementsTag struct{ JSDocTag }

// IsJSDocImplementsTag reports whether the node is a JSDocImplementsTag.
func (n Node) IsJSDocImplementsTag() bool { return ast.IsJSDocImplementsTag(n.node) }

// AsJSDocImplementsTag downcasts the node, or returns false.
func (n Node) AsJSDocImplementsTag() (JSDocImplementsTag, bool) {
	n.check()
	if !n.IsJSDocImplementsTag() {
		return JSDocImplementsTag{}, false
	}
	return JSDocImplementsTag{JSDocTag: JSDocTag{Node: n}}, true
}

// JSDocImportTag wraps a JSDocImportTag node.
type JSDocImportTag struct{ JSDocTag }

// IsJSDocImportTag reports whether the node is a JSDocImportTag.
func (n Node) IsJSDocImportTag() bool { return ast.IsJSDocImportTag(n.node) }

// AsJSDocImportTag downcasts the node, or returns false.
func (n Node) AsJSDocImportTag() (JSDocImportTag, bool) {
	n.check()
	if !n.IsJSDocImportTag() {
		return JSDocImportTag{}, false
	}
	return JSDocImportTag{JSDocTag: JSDocTag{Node: n}}, true
}

// JSDocLink wraps a JSDocLink node.
type JSDocLink struct{ Node }

// IsJSDocLink reports whether the node is a JSDocLink.
func (n Node) IsJSDocLink() bool { return ast.IsJSDocLink(n.node) }

// AsJSDocLink downcasts the node, or returns false.
func (n Node) AsJSDocLink() (JSDocLink, bool) {
	n.check()
	if !n.IsJSDocLink() {
		return JSDocLink{}, false
	}
	return JSDocLink{Node: n}, true
}

// JSDocLinkCode wraps a JSDocLinkCode node.
type JSDocLinkCode struct{ Node }

// IsJSDocLinkCode reports whether the node is a JSDocLinkCode.
func (n Node) IsJSDocLinkCode() bool { return ast.IsJSDocLinkCode(n.node) }

// AsJSDocLinkCode downcasts the node, or returns false.
func (n Node) AsJSDocLinkCode() (JSDocLinkCode, bool) {
	n.check()
	if !n.IsJSDocLinkCode() {
		return JSDocLinkCode{}, false
	}
	return JSDocLinkCode{Node: n}, true
}

// JSDocLinkPlain wraps a JSDocLinkPlain node.
type JSDocLinkPlain struct{ Node }

// IsJSDocLinkPlain reports whether the node is a JSDocLinkPlain.
func (n Node) IsJSDocLinkPlain() bool { return ast.IsJSDocLinkPlain(n.node) }

// AsJSDocLinkPlain downcasts the node, or returns false.
func (n Node) AsJSDocLinkPlain() (JSDocLinkPlain, bool) {
	n.check()
	if !n.IsJSDocLinkPlain() {
		return JSDocLinkPlain{}, false
	}
	return JSDocLinkPlain{Node: n}, true
}

// JSDocNameReference wraps a JSDocNameReference node.
type JSDocNameReference struct{ Node }

// IsJSDocNameReference reports whether the node is a JSDocNameReference.
func (n Node) IsJSDocNameReference() bool { return ast.IsJSDocNameReference(n.node) }

// AsJSDocNameReference downcasts the node, or returns false.
func (n Node) AsJSDocNameReference() (JSDocNameReference, bool) {
	n.check()
	if !n.IsJSDocNameReference() {
		return JSDocNameReference{}, false
	}
	return JSDocNameReference{Node: n}, true
}

// JSDocNonNullableType wraps a JSDocNonNullableType node.
type JSDocNonNullableType struct{ Node }

// IsJSDocNonNullableType reports whether the node is a JSDocNonNullableType.
func (n Node) IsJSDocNonNullableType() bool { return ast.IsJSDocNonNullableType(n.node) }

// AsJSDocNonNullableType downcasts the node, or returns false.
func (n Node) AsJSDocNonNullableType() (JSDocNonNullableType, bool) {
	n.check()
	if !n.IsJSDocNonNullableType() {
		return JSDocNonNullableType{}, false
	}
	return JSDocNonNullableType{Node: n}, true
}

// JSDocNullableType wraps a JSDocNullableType node.
type JSDocNullableType struct{ Node }

// IsJSDocNullableType reports whether the node is a JSDocNullableType.
func (n Node) IsJSDocNullableType() bool { return ast.IsJSDocNullableType(n.node) }

// AsJSDocNullableType downcasts the node, or returns false.
func (n Node) AsJSDocNullableType() (JSDocNullableType, bool) {
	n.check()
	if !n.IsJSDocNullableType() {
		return JSDocNullableType{}, false
	}
	return JSDocNullableType{Node: n}, true
}

// JSDocOptionalType wraps a JSDocOptionalType node.
type JSDocOptionalType struct{ Node }

// IsJSDocOptionalType reports whether the node is a JSDocOptionalType.
func (n Node) IsJSDocOptionalType() bool { return ast.IsJSDocOptionalType(n.node) }

// AsJSDocOptionalType downcasts the node, or returns false.
func (n Node) AsJSDocOptionalType() (JSDocOptionalType, bool) {
	n.check()
	if !n.IsJSDocOptionalType() {
		return JSDocOptionalType{}, false
	}
	return JSDocOptionalType{Node: n}, true
}

// JSDocOverloadTag wraps a JSDocOverloadTag node.
type JSDocOverloadTag struct{ JSDocTag }

// IsJSDocOverloadTag reports whether the node is a JSDocOverloadTag.
func (n Node) IsJSDocOverloadTag() bool { return ast.IsJSDocOverloadTag(n.node) }

// AsJSDocOverloadTag downcasts the node, or returns false.
func (n Node) AsJSDocOverloadTag() (JSDocOverloadTag, bool) {
	n.check()
	if !n.IsJSDocOverloadTag() {
		return JSDocOverloadTag{}, false
	}
	return JSDocOverloadTag{JSDocTag: JSDocTag{Node: n}}, true
}

// JSDocOverrideTag wraps a JSDocOverrideTag node.
type JSDocOverrideTag struct{ JSDocTag }

// IsJSDocOverrideTag reports whether the node is a JSDocOverrideTag.
func (n Node) IsJSDocOverrideTag() bool { return ast.IsJSDocOverrideTag(n.node) }

// AsJSDocOverrideTag downcasts the node, or returns false.
func (n Node) AsJSDocOverrideTag() (JSDocOverrideTag, bool) {
	n.check()
	if !n.IsJSDocOverrideTag() {
		return JSDocOverrideTag{}, false
	}
	return JSDocOverrideTag{JSDocTag: JSDocTag{Node: n}}, true
}

// JSDocPrivateTag wraps a JSDocPrivateTag node.
type JSDocPrivateTag struct{ JSDocTag }

// IsJSDocPrivateTag reports whether the node is a JSDocPrivateTag.
func (n Node) IsJSDocPrivateTag() bool { return ast.IsJSDocPrivateTag(n.node) }

// AsJSDocPrivateTag downcasts the node, or returns false.
func (n Node) AsJSDocPrivateTag() (JSDocPrivateTag, bool) {
	n.check()
	if !n.IsJSDocPrivateTag() {
		return JSDocPrivateTag{}, false
	}
	return JSDocPrivateTag{JSDocTag: JSDocTag{Node: n}}, true
}

// JSDocProtectedTag wraps a JSDocProtectedTag node.
type JSDocProtectedTag struct{ JSDocTag }

// IsJSDocProtectedTag reports whether the node is a JSDocProtectedTag.
func (n Node) IsJSDocProtectedTag() bool { return ast.IsJSDocProtectedTag(n.node) }

// AsJSDocProtectedTag downcasts the node, or returns false.
func (n Node) AsJSDocProtectedTag() (JSDocProtectedTag, bool) {
	n.check()
	if !n.IsJSDocProtectedTag() {
		return JSDocProtectedTag{}, false
	}
	return JSDocProtectedTag{JSDocTag: JSDocTag{Node: n}}, true
}

// JSDocPublicTag wraps a JSDocPublicTag node.
type JSDocPublicTag struct{ JSDocTag }

// IsJSDocPublicTag reports whether the node is a JSDocPublicTag.
func (n Node) IsJSDocPublicTag() bool { return ast.IsJSDocPublicTag(n.node) }

// AsJSDocPublicTag downcasts the node, or returns false.
func (n Node) AsJSDocPublicTag() (JSDocPublicTag, bool) {
	n.check()
	if !n.IsJSDocPublicTag() {
		return JSDocPublicTag{}, false
	}
	return JSDocPublicTag{JSDocTag: JSDocTag{Node: n}}, true
}

// JSDocReadonlyTag wraps a JSDocReadonlyTag node.
type JSDocReadonlyTag struct{ JSDocTag }

// IsJSDocReadonlyTag reports whether the node is a JSDocReadonlyTag.
func (n Node) IsJSDocReadonlyTag() bool { return ast.IsJSDocReadonlyTag(n.node) }

// AsJSDocReadonlyTag downcasts the node, or returns false.
func (n Node) AsJSDocReadonlyTag() (JSDocReadonlyTag, bool) {
	n.check()
	if !n.IsJSDocReadonlyTag() {
		return JSDocReadonlyTag{}, false
	}
	return JSDocReadonlyTag{JSDocTag: JSDocTag{Node: n}}, true
}

// JSDocReturnTag wraps a JSDocReturnTag node.
type JSDocReturnTag struct{ JSDocTag }

// IsJSDocReturnTag reports whether the node is a JSDocReturnTag.
func (n Node) IsJSDocReturnTag() bool { return ast.IsJSDocReturnTag(n.node) }

// AsJSDocReturnTag downcasts the node, or returns false.
func (n Node) AsJSDocReturnTag() (JSDocReturnTag, bool) {
	n.check()
	if !n.IsJSDocReturnTag() {
		return JSDocReturnTag{}, false
	}
	return JSDocReturnTag{JSDocTag: JSDocTag{Node: n}}, true
}

// JSDocSatisfiesTag wraps a JSDocSatisfiesTag node.
type JSDocSatisfiesTag struct{ JSDocTag }

// IsJSDocSatisfiesTag reports whether the node is a JSDocSatisfiesTag.
func (n Node) IsJSDocSatisfiesTag() bool { return ast.IsJSDocSatisfiesTag(n.node) }

// AsJSDocSatisfiesTag downcasts the node, or returns false.
func (n Node) AsJSDocSatisfiesTag() (JSDocSatisfiesTag, bool) {
	n.check()
	if !n.IsJSDocSatisfiesTag() {
		return JSDocSatisfiesTag{}, false
	}
	return JSDocSatisfiesTag{JSDocTag: JSDocTag{Node: n}}, true
}

// JSDocSeeTag wraps a JSDocSeeTag node.
type JSDocSeeTag struct{ JSDocTag }

// IsJSDocSeeTag reports whether the node is a JSDocSeeTag.
func (n Node) IsJSDocSeeTag() bool { return ast.IsJSDocSeeTag(n.node) }

// AsJSDocSeeTag downcasts the node, or returns false.
func (n Node) AsJSDocSeeTag() (JSDocSeeTag, bool) {
	n.check()
	if !n.IsJSDocSeeTag() {
		return JSDocSeeTag{}, false
	}
	return JSDocSeeTag{JSDocTag: JSDocTag{Node: n}}, true
}

// JSDocSignature wraps a JSDocSignature node.
type JSDocSignature struct{ Node }

// IsJSDocSignature reports whether the node is a JSDocSignature.
func (n Node) IsJSDocSignature() bool { return ast.IsJSDocSignature(n.node) }

// AsJSDocSignature downcasts the node, or returns false.
func (n Node) AsJSDocSignature() (JSDocSignature, bool) {
	n.check()
	if !n.IsJSDocSignature() {
		return JSDocSignature{}, false
	}
	return JSDocSignature{Node: n}, true
}

// JSDocTemplateTag wraps a JSDocTemplateTag node.
type JSDocTemplateTag struct{ JSDocTag }

// IsJSDocTemplateTag reports whether the node is a JSDocTemplateTag.
func (n Node) IsJSDocTemplateTag() bool { return ast.IsJSDocTemplateTag(n.node) }

// AsJSDocTemplateTag downcasts the node, or returns false.
func (n Node) AsJSDocTemplateTag() (JSDocTemplateTag, bool) {
	n.check()
	if !n.IsJSDocTemplateTag() {
		return JSDocTemplateTag{}, false
	}
	return JSDocTemplateTag{JSDocTag: JSDocTag{Node: n}}, true
}

// JSDocText wraps a JSDocText node.
type JSDocText struct{ Node }

// IsJSDocText reports whether the node is a JSDocText.
func (n Node) IsJSDocText() bool { return ast.IsJSDocText(n.node) }

// AsJSDocText downcasts the node, or returns false.
func (n Node) AsJSDocText() (JSDocText, bool) {
	n.check()
	if !n.IsJSDocText() {
		return JSDocText{}, false
	}
	return JSDocText{Node: n}, true
}

// JSDocThisTag wraps a JSDocThisTag node.
type JSDocThisTag struct{ JSDocTag }

// IsJSDocThisTag reports whether the node is a JSDocThisTag.
func (n Node) IsJSDocThisTag() bool { return ast.IsJSDocThisTag(n.node) }

// AsJSDocThisTag downcasts the node, or returns false.
func (n Node) AsJSDocThisTag() (JSDocThisTag, bool) {
	n.check()
	if !n.IsJSDocThisTag() {
		return JSDocThisTag{}, false
	}
	return JSDocThisTag{JSDocTag: JSDocTag{Node: n}}, true
}

// JSDocThrowsTag wraps a JSDocThrowsTag node.
type JSDocThrowsTag struct{ JSDocTag }

// IsJSDocThrowsTag reports whether the node is a JSDocThrowsTag.
func (n Node) IsJSDocThrowsTag() bool { return ast.IsJSDocThrowsTag(n.node) }

// AsJSDocThrowsTag downcasts the node, or returns false.
func (n Node) AsJSDocThrowsTag() (JSDocThrowsTag, bool) {
	n.check()
	if !n.IsJSDocThrowsTag() {
		return JSDocThrowsTag{}, false
	}
	return JSDocThrowsTag{JSDocTag: JSDocTag{Node: n}}, true
}

// JSDocTypeExpression wraps a JSDocTypeExpression node.
type JSDocTypeExpression struct{ Node }

// IsJSDocTypeExpression reports whether the node is a JSDocTypeExpression.
func (n Node) IsJSDocTypeExpression() bool { return ast.IsJSDocTypeExpression(n.node) }

// AsJSDocTypeExpression downcasts the node, or returns false.
func (n Node) AsJSDocTypeExpression() (JSDocTypeExpression, bool) {
	n.check()
	if !n.IsJSDocTypeExpression() {
		return JSDocTypeExpression{}, false
	}
	return JSDocTypeExpression{Node: n}, true
}

// JSDocTypeLiteral wraps a JSDocTypeLiteral node.
type JSDocTypeLiteral struct{ Node }

// IsJSDocTypeLiteral reports whether the node is a JSDocTypeLiteral.
func (n Node) IsJSDocTypeLiteral() bool { return ast.IsJSDocTypeLiteral(n.node) }

// AsJSDocTypeLiteral downcasts the node, or returns false.
func (n Node) AsJSDocTypeLiteral() (JSDocTypeLiteral, bool) {
	n.check()
	if !n.IsJSDocTypeLiteral() {
		return JSDocTypeLiteral{}, false
	}
	return JSDocTypeLiteral{Node: n}, true
}

// JSDocTypeTag wraps a JSDocTypeTag node.
type JSDocTypeTag struct{ JSDocTag }

// IsJSDocTypeTag reports whether the node is a JSDocTypeTag.
func (n Node) IsJSDocTypeTag() bool { return ast.IsJSDocTypeTag(n.node) }

// AsJSDocTypeTag downcasts the node, or returns false.
func (n Node) AsJSDocTypeTag() (JSDocTypeTag, bool) {
	n.check()
	if !n.IsJSDocTypeTag() {
		return JSDocTypeTag{}, false
	}
	return JSDocTypeTag{JSDocTag: JSDocTag{Node: n}}, true
}

// JSDocTypedefTag wraps a JSDocTypedefTag node.
type JSDocTypedefTag struct{ JSDocTag }

// IsJSDocTypedefTag reports whether the node is a JSDocTypedefTag.
func (n Node) IsJSDocTypedefTag() bool { return ast.IsJSDocTypedefTag(n.node) }

// AsJSDocTypedefTag downcasts the node, or returns false.
func (n Node) AsJSDocTypedefTag() (JSDocTypedefTag, bool) {
	n.check()
	if !n.IsJSDocTypedefTag() {
		return JSDocTypedefTag{}, false
	}
	return JSDocTypedefTag{JSDocTag: JSDocTag{Node: n}}, true
}

// JSDocUnknownTag wraps a JSDocUnknownTag node.
type JSDocUnknownTag struct{ JSDocTag }

// IsJSDocUnknownTag reports whether the node is a JSDocUnknownTag.
func (n Node) IsJSDocUnknownTag() bool { return ast.IsJSDocUnknownTag(n.node) }

// AsJSDocUnknownTag downcasts the node, or returns false.
func (n Node) AsJSDocUnknownTag() (JSDocUnknownTag, bool) {
	n.check()
	if !n.IsJSDocUnknownTag() {
		return JSDocUnknownTag{}, false
	}
	return JSDocUnknownTag{JSDocTag: JSDocTag{Node: n}}, true
}

// JSDocVariadicType wraps a JSDocVariadicType node.
type JSDocVariadicType struct{ Node }

// IsJSDocVariadicType reports whether the node is a JSDocVariadicType.
func (n Node) IsJSDocVariadicType() bool { return ast.IsJSDocVariadicType(n.node) }

// AsJSDocVariadicType downcasts the node, or returns false.
func (n Node) AsJSDocVariadicType() (JSDocVariadicType, bool) {
	n.check()
	if !n.IsJSDocVariadicType() {
		return JSDocVariadicType{}, false
	}
	return JSDocVariadicType{Node: n}, true
}

// JsxAttributes wraps a JsxAttributes node.
type JsxAttributes struct{ Node }

// IsJsxAttributes reports whether the node is a JsxAttributes.
func (n Node) IsJsxAttributes() bool { return ast.IsJsxAttributes(n.node) }

// AsJsxAttributes downcasts the node, or returns false.
func (n Node) AsJsxAttributes() (JsxAttributes, bool) {
	n.check()
	if !n.IsJsxAttributes() {
		return JsxAttributes{}, false
	}
	return JsxAttributes{Node: n}, true
}

// JsxClosingElement wraps a JsxClosingElement node.
type JsxClosingElement struct{ Node }

// IsJsxClosingElement reports whether the node is a JsxClosingElement.
func (n Node) IsJsxClosingElement() bool { return ast.IsJsxClosingElement(n.node) }

// AsJsxClosingElement downcasts the node, or returns false.
func (n Node) AsJsxClosingElement() (JsxClosingElement, bool) {
	n.check()
	if !n.IsJsxClosingElement() {
		return JsxClosingElement{}, false
	}
	return JsxClosingElement{Node: n}, true
}

// JsxClosingFragment wraps a JsxClosingFragment node.
type JsxClosingFragment struct{ Node }

// IsJsxClosingFragment reports whether the node is a JsxClosingFragment.
func (n Node) IsJsxClosingFragment() bool { return ast.IsJsxClosingFragment(n.node) }

// AsJsxClosingFragment downcasts the node, or returns false.
func (n Node) AsJsxClosingFragment() (JsxClosingFragment, bool) {
	n.check()
	if !n.IsJsxClosingFragment() {
		return JsxClosingFragment{}, false
	}
	return JsxClosingFragment{Node: n}, true
}

// JsxExpression wraps a JsxExpression node.
type JsxExpression struct{ Node }

// IsJsxExpression reports whether the node is a JsxExpression.
func (n Node) IsJsxExpression() bool { return ast.IsJsxExpression(n.node) }

// AsJsxExpression downcasts the node, or returns false.
func (n Node) AsJsxExpression() (JsxExpression, bool) {
	n.check()
	if !n.IsJsxExpression() {
		return JsxExpression{}, false
	}
	return JsxExpression{Node: n}, true
}

// JsxFragment wraps a JsxFragment node.
type JsxFragment struct{ Node }

// IsJsxFragment reports whether the node is a JsxFragment.
func (n Node) IsJsxFragment() bool { return ast.IsJsxFragment(n.node) }

// AsJsxFragment downcasts the node, or returns false.
func (n Node) AsJsxFragment() (JsxFragment, bool) {
	n.check()
	if !n.IsJsxFragment() {
		return JsxFragment{}, false
	}
	return JsxFragment{Node: n}, true
}

// JsxNamespacedName wraps a JsxNamespacedName node.
type JsxNamespacedName struct{ Node }

// IsJsxNamespacedName reports whether the node is a JsxNamespacedName.
func (n Node) IsJsxNamespacedName() bool { return ast.IsJsxNamespacedName(n.node) }

// AsJsxNamespacedName downcasts the node, or returns false.
func (n Node) AsJsxNamespacedName() (JsxNamespacedName, bool) {
	n.check()
	if !n.IsJsxNamespacedName() {
		return JsxNamespacedName{}, false
	}
	return JsxNamespacedName{Node: n}, true
}

// JsxOpeningElement wraps a JsxOpeningElement node.
type JsxOpeningElement struct{ Node }

// IsJsxOpeningElement reports whether the node is a JsxOpeningElement.
func (n Node) IsJsxOpeningElement() bool { return ast.IsJsxOpeningElement(n.node) }

// AsJsxOpeningElement downcasts the node, or returns false.
func (n Node) AsJsxOpeningElement() (JsxOpeningElement, bool) {
	n.check()
	if !n.IsJsxOpeningElement() {
		return JsxOpeningElement{}, false
	}
	return JsxOpeningElement{Node: n}, true
}

// JsxOpeningFragment wraps a JsxOpeningFragment node.
type JsxOpeningFragment struct{ Node }

// IsJsxOpeningFragment reports whether the node is a JsxOpeningFragment.
func (n Node) IsJsxOpeningFragment() bool { return ast.IsJsxOpeningFragment(n.node) }

// AsJsxOpeningFragment downcasts the node, or returns false.
func (n Node) AsJsxOpeningFragment() (JsxOpeningFragment, bool) {
	n.check()
	if !n.IsJsxOpeningFragment() {
		return JsxOpeningFragment{}, false
	}
	return JsxOpeningFragment{Node: n}, true
}

// JsxSelfClosingElement wraps a JsxSelfClosingElement node.
type JsxSelfClosingElement struct{ Node }

// IsJsxSelfClosingElement reports whether the node is a JsxSelfClosingElement.
func (n Node) IsJsxSelfClosingElement() bool { return ast.IsJsxSelfClosingElement(n.node) }

// AsJsxSelfClosingElement downcasts the node, or returns false.
func (n Node) AsJsxSelfClosingElement() (JsxSelfClosingElement, bool) {
	n.check()
	if !n.IsJsxSelfClosingElement() {
		return JsxSelfClosingElement{}, false
	}
	return JsxSelfClosingElement{Node: n}, true
}

// JsxSpreadAttribute wraps a JsxSpreadAttribute node.
type JsxSpreadAttribute struct{ Node }

// IsJsxSpreadAttribute reports whether the node is a JsxSpreadAttribute.
func (n Node) IsJsxSpreadAttribute() bool { return ast.IsJsxSpreadAttribute(n.node) }

// AsJsxSpreadAttribute downcasts the node, or returns false.
func (n Node) AsJsxSpreadAttribute() (JsxSpreadAttribute, bool) {
	n.check()
	if !n.IsJsxSpreadAttribute() {
		return JsxSpreadAttribute{}, false
	}
	return JsxSpreadAttribute{Node: n}, true
}

// LabeledStatement wraps a LabeledStatement node.
type LabeledStatement struct{ Node }

// IsLabeledStatement reports whether the node is a LabeledStatement.
func (n Node) IsLabeledStatement() bool { return ast.IsLabeledStatement(n.node) }

// AsLabeledStatement downcasts the node, or returns false.
func (n Node) AsLabeledStatement() (LabeledStatement, bool) {
	n.check()
	if !n.IsLabeledStatement() {
		return LabeledStatement{}, false
	}
	return LabeledStatement{Node: n}, true
}

// LiteralTypeNode wraps a LiteralTypeNode node.
type LiteralTypeNode struct{ Node }

// IsLiteralTypeNode reports whether the node is a LiteralTypeNode.
func (n Node) IsLiteralTypeNode() bool { return ast.IsLiteralTypeNode(n.node) }

// AsLiteralTypeNode downcasts the node, or returns false.
func (n Node) AsLiteralTypeNode() (LiteralTypeNode, bool) {
	n.check()
	if !n.IsLiteralTypeNode() {
		return LiteralTypeNode{}, false
	}
	return LiteralTypeNode{Node: n}, true
}

// MappedTypeNode wraps a MappedTypeNode node.
type MappedTypeNode struct{ Node }

// IsMappedTypeNode reports whether the node is a MappedTypeNode.
func (n Node) IsMappedTypeNode() bool { return ast.IsMappedTypeNode(n.node) }

// AsMappedTypeNode downcasts the node, or returns false.
func (n Node) AsMappedTypeNode() (MappedTypeNode, bool) {
	n.check()
	if !n.IsMappedTypeNode() {
		return MappedTypeNode{}, false
	}
	return MappedTypeNode{Node: n}, true
}

// MetaProperty wraps a MetaProperty node.
type MetaProperty struct{ Node }

// IsMetaProperty reports whether the node is a MetaProperty.
func (n Node) IsMetaProperty() bool { return ast.IsMetaProperty(n.node) }

// AsMetaProperty downcasts the node, or returns false.
func (n Node) AsMetaProperty() (MetaProperty, bool) {
	n.check()
	if !n.IsMetaProperty() {
		return MetaProperty{}, false
	}
	return MetaProperty{Node: n}, true
}

// MethodSignatureDeclaration wraps a MethodSignatureDeclaration node.
type MethodSignatureDeclaration struct{ Node }

// IsMethodSignatureDeclaration reports whether the node is a MethodSignatureDeclaration.
func (n Node) IsMethodSignatureDeclaration() bool { return ast.IsMethodSignatureDeclaration(n.node) }

// AsMethodSignatureDeclaration downcasts the node, or returns false.
func (n Node) AsMethodSignatureDeclaration() (MethodSignatureDeclaration, bool) {
	n.check()
	if !n.IsMethodSignatureDeclaration() {
		return MethodSignatureDeclaration{}, false
	}
	return MethodSignatureDeclaration{Node: n}, true
}

// ModuleBlock wraps a ModuleBlock node.
type ModuleBlock struct{ Node }

// IsModuleBlock reports whether the node is a ModuleBlock.
func (n Node) IsModuleBlock() bool { return ast.IsModuleBlock(n.node) }

// AsModuleBlock downcasts the node, or returns false.
func (n Node) AsModuleBlock() (ModuleBlock, bool) {
	n.check()
	if !n.IsModuleBlock() {
		return ModuleBlock{}, false
	}
	return ModuleBlock{Node: n}, true
}

// ModuleDeclaration wraps a ModuleDeclaration node.
type ModuleDeclaration struct{ Node }

// IsModuleDeclaration reports whether the node is a ModuleDeclaration.
func (n Node) IsModuleDeclaration() bool { return ast.IsModuleDeclaration(n.node) }

// AsModuleDeclaration downcasts the node, or returns false.
func (n Node) AsModuleDeclaration() (ModuleDeclaration, bool) {
	n.check()
	if !n.IsModuleDeclaration() {
		return ModuleDeclaration{}, false
	}
	return ModuleDeclaration{Node: n}, true
}

// NamedExports wraps a NamedExports node.
type NamedExports struct{ Node }

// IsNamedExports reports whether the node is a NamedExports.
func (n Node) IsNamedExports() bool { return ast.IsNamedExports(n.node) }

// AsNamedExports downcasts the node, or returns false.
func (n Node) AsNamedExports() (NamedExports, bool) {
	n.check()
	if !n.IsNamedExports() {
		return NamedExports{}, false
	}
	return NamedExports{Node: n}, true
}

// NamedImports wraps a NamedImports node.
type NamedImports struct{ Node }

// IsNamedImports reports whether the node is a NamedImports.
func (n Node) IsNamedImports() bool { return ast.IsNamedImports(n.node) }

// AsNamedImports downcasts the node, or returns false.
func (n Node) AsNamedImports() (NamedImports, bool) {
	n.check()
	if !n.IsNamedImports() {
		return NamedImports{}, false
	}
	return NamedImports{Node: n}, true
}

// NamedTupleMember wraps a NamedTupleMember node.
type NamedTupleMember struct{ Node }

// IsNamedTupleMember reports whether the node is a NamedTupleMember.
func (n Node) IsNamedTupleMember() bool { return ast.IsNamedTupleMember(n.node) }

// AsNamedTupleMember downcasts the node, or returns false.
func (n Node) AsNamedTupleMember() (NamedTupleMember, bool) {
	n.check()
	if !n.IsNamedTupleMember() {
		return NamedTupleMember{}, false
	}
	return NamedTupleMember{Node: n}, true
}

// NamespaceExport wraps a NamespaceExport node.
type NamespaceExport struct{ Node }

// IsNamespaceExport reports whether the node is a NamespaceExport.
func (n Node) IsNamespaceExport() bool { return ast.IsNamespaceExport(n.node) }

// AsNamespaceExport downcasts the node, or returns false.
func (n Node) AsNamespaceExport() (NamespaceExport, bool) {
	n.check()
	if !n.IsNamespaceExport() {
		return NamespaceExport{}, false
	}
	return NamespaceExport{Node: n}, true
}

// NamespaceExportDeclaration wraps a NamespaceExportDeclaration node.
type NamespaceExportDeclaration struct{ Node }

// IsNamespaceExportDeclaration reports whether the node is a NamespaceExportDeclaration.
func (n Node) IsNamespaceExportDeclaration() bool { return ast.IsNamespaceExportDeclaration(n.node) }

// AsNamespaceExportDeclaration downcasts the node, or returns false.
func (n Node) AsNamespaceExportDeclaration() (NamespaceExportDeclaration, bool) {
	n.check()
	if !n.IsNamespaceExportDeclaration() {
		return NamespaceExportDeclaration{}, false
	}
	return NamespaceExportDeclaration{Node: n}, true
}

// NamespaceImport wraps a NamespaceImport node.
type NamespaceImport struct{ Node }

// IsNamespaceImport reports whether the node is a NamespaceImport.
func (n Node) IsNamespaceImport() bool { return ast.IsNamespaceImport(n.node) }

// AsNamespaceImport downcasts the node, or returns false.
func (n Node) AsNamespaceImport() (NamespaceImport, bool) {
	n.check()
	if !n.IsNamespaceImport() {
		return NamespaceImport{}, false
	}
	return NamespaceImport{Node: n}, true
}

// NewExpression wraps a NewExpression node.
type NewExpression struct{ Node }

// IsNewExpression reports whether the node is a NewExpression.
func (n Node) IsNewExpression() bool { return ast.IsNewExpression(n.node) }

// AsNewExpression downcasts the node, or returns false.
func (n Node) AsNewExpression() (NewExpression, bool) {
	n.check()
	if !n.IsNewExpression() {
		return NewExpression{}, false
	}
	return NewExpression{Node: n}, true
}

// NoSubstitutionTemplateLiteral wraps a NoSubstitutionTemplateLiteral node.
type NoSubstitutionTemplateLiteral struct{ Node }

// IsNoSubstitutionTemplateLiteral reports whether the node is a NoSubstitutionTemplateLiteral.
func (n Node) IsNoSubstitutionTemplateLiteral() bool {
	return ast.IsNoSubstitutionTemplateLiteral(n.node)
}

// AsNoSubstitutionTemplateLiteral downcasts the node, or returns false.
func (n Node) AsNoSubstitutionTemplateLiteral() (NoSubstitutionTemplateLiteral, bool) {
	n.check()
	if !n.IsNoSubstitutionTemplateLiteral() {
		return NoSubstitutionTemplateLiteral{}, false
	}
	return NoSubstitutionTemplateLiteral{Node: n}, true
}

// NonNullExpression wraps a NonNullExpression node.
type NonNullExpression struct{ Node }

// IsNonNullExpression reports whether the node is a NonNullExpression.
func (n Node) IsNonNullExpression() bool { return ast.IsNonNullExpression(n.node) }

// AsNonNullExpression downcasts the node, or returns false.
func (n Node) AsNonNullExpression() (NonNullExpression, bool) {
	n.check()
	if !n.IsNonNullExpression() {
		return NonNullExpression{}, false
	}
	return NonNullExpression{Node: n}, true
}

// NumericLiteral wraps a NumericLiteral node.
type NumericLiteral struct{ Node }

// IsNumericLiteral reports whether the node is a NumericLiteral.
func (n Node) IsNumericLiteral() bool { return ast.IsNumericLiteral(n.node) }

// AsNumericLiteral downcasts the node, or returns false.
func (n Node) AsNumericLiteral() (NumericLiteral, bool) {
	n.check()
	if !n.IsNumericLiteral() {
		return NumericLiteral{}, false
	}
	return NumericLiteral{Node: n}, true
}

// ObjectLiteralExpression wraps a ObjectLiteralExpression node.
type ObjectLiteralExpression struct{ Node }

// IsObjectLiteralExpression reports whether the node is a ObjectLiteralExpression.
func (n Node) IsObjectLiteralExpression() bool { return ast.IsObjectLiteralExpression(n.node) }

// AsObjectLiteralExpression downcasts the node, or returns false.
func (n Node) AsObjectLiteralExpression() (ObjectLiteralExpression, bool) {
	n.check()
	if !n.IsObjectLiteralExpression() {
		return ObjectLiteralExpression{}, false
	}
	return ObjectLiteralExpression{Node: n}, true
}

// OptionalTypeNode wraps a OptionalTypeNode node.
type OptionalTypeNode struct{ Node }

// IsOptionalTypeNode reports whether the node is a OptionalTypeNode.
func (n Node) IsOptionalTypeNode() bool { return ast.IsOptionalTypeNode(n.node) }

// AsOptionalTypeNode downcasts the node, or returns false.
func (n Node) AsOptionalTypeNode() (OptionalTypeNode, bool) {
	n.check()
	if !n.IsOptionalTypeNode() {
		return OptionalTypeNode{}, false
	}
	return OptionalTypeNode{Node: n}, true
}

// ParenthesizedExpression wraps a ParenthesizedExpression node.
type ParenthesizedExpression struct{ Node }

// IsParenthesizedExpression reports whether the node is a ParenthesizedExpression.
func (n Node) IsParenthesizedExpression() bool { return ast.IsParenthesizedExpression(n.node) }

// AsParenthesizedExpression downcasts the node, or returns false.
func (n Node) AsParenthesizedExpression() (ParenthesizedExpression, bool) {
	n.check()
	if !n.IsParenthesizedExpression() {
		return ParenthesizedExpression{}, false
	}
	return ParenthesizedExpression{Node: n}, true
}

// ParenthesizedTypeNode wraps a ParenthesizedTypeNode node.
type ParenthesizedTypeNode struct{ Node }

// IsParenthesizedTypeNode reports whether the node is a ParenthesizedTypeNode.
func (n Node) IsParenthesizedTypeNode() bool { return ast.IsParenthesizedTypeNode(n.node) }

// AsParenthesizedTypeNode downcasts the node, or returns false.
func (n Node) AsParenthesizedTypeNode() (ParenthesizedTypeNode, bool) {
	n.check()
	if !n.IsParenthesizedTypeNode() {
		return ParenthesizedTypeNode{}, false
	}
	return ParenthesizedTypeNode{Node: n}, true
}

// PostfixUnaryExpression wraps a PostfixUnaryExpression node.
type PostfixUnaryExpression struct{ Node }

// IsPostfixUnaryExpression reports whether the node is a PostfixUnaryExpression.
func (n Node) IsPostfixUnaryExpression() bool { return ast.IsPostfixUnaryExpression(n.node) }

// AsPostfixUnaryExpression downcasts the node, or returns false.
func (n Node) AsPostfixUnaryExpression() (PostfixUnaryExpression, bool) {
	n.check()
	if !n.IsPostfixUnaryExpression() {
		return PostfixUnaryExpression{}, false
	}
	return PostfixUnaryExpression{Node: n}, true
}

// PrefixUnaryExpression wraps a PrefixUnaryExpression node.
type PrefixUnaryExpression struct{ Node }

// IsPrefixUnaryExpression reports whether the node is a PrefixUnaryExpression.
func (n Node) IsPrefixUnaryExpression() bool { return ast.IsPrefixUnaryExpression(n.node) }

// AsPrefixUnaryExpression downcasts the node, or returns false.
func (n Node) AsPrefixUnaryExpression() (PrefixUnaryExpression, bool) {
	n.check()
	if !n.IsPrefixUnaryExpression() {
		return PrefixUnaryExpression{}, false
	}
	return PrefixUnaryExpression{Node: n}, true
}

// PrivateIdentifier wraps a PrivateIdentifier node.
type PrivateIdentifier struct{ Node }

// IsPrivateIdentifier reports whether the node is a PrivateIdentifier.
func (n Node) IsPrivateIdentifier() bool { return ast.IsPrivateIdentifier(n.node) }

// AsPrivateIdentifier downcasts the node, or returns false.
func (n Node) AsPrivateIdentifier() (PrivateIdentifier, bool) {
	n.check()
	if !n.IsPrivateIdentifier() {
		return PrivateIdentifier{}, false
	}
	return PrivateIdentifier{Node: n}, true
}

// PropertyAssignment wraps a PropertyAssignment node.
type PropertyAssignment struct{ Node }

// IsPropertyAssignment reports whether the node is a PropertyAssignment.
func (n Node) IsPropertyAssignment() bool { return ast.IsPropertyAssignment(n.node) }

// AsPropertyAssignment downcasts the node, or returns false.
func (n Node) AsPropertyAssignment() (PropertyAssignment, bool) {
	n.check()
	if !n.IsPropertyAssignment() {
		return PropertyAssignment{}, false
	}
	return PropertyAssignment{Node: n}, true
}

// PropertySignatureDeclaration wraps a PropertySignatureDeclaration node.
type PropertySignatureDeclaration struct{ Node }

// IsPropertySignatureDeclaration reports whether the node is a PropertySignatureDeclaration.
func (n Node) IsPropertySignatureDeclaration() bool {
	return ast.IsPropertySignatureDeclaration(n.node)
}

// AsPropertySignatureDeclaration downcasts the node, or returns false.
func (n Node) AsPropertySignatureDeclaration() (PropertySignatureDeclaration, bool) {
	n.check()
	if !n.IsPropertySignatureDeclaration() {
		return PropertySignatureDeclaration{}, false
	}
	return PropertySignatureDeclaration{Node: n}, true
}

// QualifiedName wraps a QualifiedName node.
type QualifiedName struct{ Node }

// IsQualifiedName reports whether the node is a QualifiedName.
func (n Node) IsQualifiedName() bool { return ast.IsQualifiedName(n.node) }

// AsQualifiedName downcasts the node, or returns false.
func (n Node) AsQualifiedName() (QualifiedName, bool) {
	n.check()
	if !n.IsQualifiedName() {
		return QualifiedName{}, false
	}
	return QualifiedName{Node: n}, true
}

// RegularExpressionLiteral wraps a RegularExpressionLiteral node.
type RegularExpressionLiteral struct{ Node }

// IsRegularExpressionLiteral reports whether the node is a RegularExpressionLiteral.
func (n Node) IsRegularExpressionLiteral() bool { return ast.IsRegularExpressionLiteral(n.node) }

// AsRegularExpressionLiteral downcasts the node, or returns false.
func (n Node) AsRegularExpressionLiteral() (RegularExpressionLiteral, bool) {
	n.check()
	if !n.IsRegularExpressionLiteral() {
		return RegularExpressionLiteral{}, false
	}
	return RegularExpressionLiteral{Node: n}, true
}

// RestTypeNode wraps a RestTypeNode node.
type RestTypeNode struct{ Node }

// IsRestTypeNode reports whether the node is a RestTypeNode.
func (n Node) IsRestTypeNode() bool { return ast.IsRestTypeNode(n.node) }

// AsRestTypeNode downcasts the node, or returns false.
func (n Node) AsRestTypeNode() (RestTypeNode, bool) {
	n.check()
	if !n.IsRestTypeNode() {
		return RestTypeNode{}, false
	}
	return RestTypeNode{Node: n}, true
}

// ReturnStatement wraps a ReturnStatement node.
type ReturnStatement struct{ Node }

// IsReturnStatement reports whether the node is a ReturnStatement.
func (n Node) IsReturnStatement() bool { return ast.IsReturnStatement(n.node) }

// AsReturnStatement downcasts the node, or returns false.
func (n Node) AsReturnStatement() (ReturnStatement, bool) {
	n.check()
	if !n.IsReturnStatement() {
		return ReturnStatement{}, false
	}
	return ReturnStatement{Node: n}, true
}

// SatisfiesExpression wraps a SatisfiesExpression node.
type SatisfiesExpression struct{ Node }

// IsSatisfiesExpression reports whether the node is a SatisfiesExpression.
func (n Node) IsSatisfiesExpression() bool { return ast.IsSatisfiesExpression(n.node) }

// AsSatisfiesExpression downcasts the node, or returns false.
func (n Node) AsSatisfiesExpression() (SatisfiesExpression, bool) {
	n.check()
	if !n.IsSatisfiesExpression() {
		return SatisfiesExpression{}, false
	}
	return SatisfiesExpression{Node: n}, true
}

// SetAccessorDeclaration wraps a SetAccessorDeclaration node.
type SetAccessorDeclaration struct{ Node }

// IsSetAccessorDeclaration reports whether the node is a SetAccessorDeclaration.
func (n Node) IsSetAccessorDeclaration() bool { return ast.IsSetAccessorDeclaration(n.node) }

// AsSetAccessorDeclaration downcasts the node, or returns false.
func (n Node) AsSetAccessorDeclaration() (SetAccessorDeclaration, bool) {
	n.check()
	if !n.IsSetAccessorDeclaration() {
		return SetAccessorDeclaration{}, false
	}
	return SetAccessorDeclaration{Node: n}, true
}

// ShorthandPropertyAssignment wraps a ShorthandPropertyAssignment node.
type ShorthandPropertyAssignment struct{ Node }

// IsShorthandPropertyAssignment reports whether the node is a ShorthandPropertyAssignment.
func (n Node) IsShorthandPropertyAssignment() bool { return ast.IsShorthandPropertyAssignment(n.node) }

// AsShorthandPropertyAssignment downcasts the node, or returns false.
func (n Node) AsShorthandPropertyAssignment() (ShorthandPropertyAssignment, bool) {
	n.check()
	if !n.IsShorthandPropertyAssignment() {
		return ShorthandPropertyAssignment{}, false
	}
	return ShorthandPropertyAssignment{Node: n}, true
}

// SpreadAssignment wraps a SpreadAssignment node.
type SpreadAssignment struct{ Node }

// IsSpreadAssignment reports whether the node is a SpreadAssignment.
func (n Node) IsSpreadAssignment() bool { return ast.IsSpreadAssignment(n.node) }

// AsSpreadAssignment downcasts the node, or returns false.
func (n Node) AsSpreadAssignment() (SpreadAssignment, bool) {
	n.check()
	if !n.IsSpreadAssignment() {
		return SpreadAssignment{}, false
	}
	return SpreadAssignment{Node: n}, true
}

// SpreadElement wraps a SpreadElement node.
type SpreadElement struct{ Node }

// IsSpreadElement reports whether the node is a SpreadElement.
func (n Node) IsSpreadElement() bool { return ast.IsSpreadElement(n.node) }

// AsSpreadElement downcasts the node, or returns false.
func (n Node) AsSpreadElement() (SpreadElement, bool) {
	n.check()
	if !n.IsSpreadElement() {
		return SpreadElement{}, false
	}
	return SpreadElement{Node: n}, true
}

// SwitchStatement wraps a SwitchStatement node.
type SwitchStatement struct{ Node }

// IsSwitchStatement reports whether the node is a SwitchStatement.
func (n Node) IsSwitchStatement() bool { return ast.IsSwitchStatement(n.node) }

// AsSwitchStatement downcasts the node, or returns false.
func (n Node) AsSwitchStatement() (SwitchStatement, bool) {
	n.check()
	if !n.IsSwitchStatement() {
		return SwitchStatement{}, false
	}
	return SwitchStatement{Node: n}, true
}

// TaggedTemplateExpression wraps a TaggedTemplateExpression node.
type TaggedTemplateExpression struct{ Node }

// IsTaggedTemplateExpression reports whether the node is a TaggedTemplateExpression.
func (n Node) IsTaggedTemplateExpression() bool { return ast.IsTaggedTemplateExpression(n.node) }

// AsTaggedTemplateExpression downcasts the node, or returns false.
func (n Node) AsTaggedTemplateExpression() (TaggedTemplateExpression, bool) {
	n.check()
	if !n.IsTaggedTemplateExpression() {
		return TaggedTemplateExpression{}, false
	}
	return TaggedTemplateExpression{Node: n}, true
}

// TemplateExpression wraps a TemplateExpression node.
type TemplateExpression struct{ Node }

// IsTemplateExpression reports whether the node is a TemplateExpression.
func (n Node) IsTemplateExpression() bool { return ast.IsTemplateExpression(n.node) }

// AsTemplateExpression downcasts the node, or returns false.
func (n Node) AsTemplateExpression() (TemplateExpression, bool) {
	n.check()
	if !n.IsTemplateExpression() {
		return TemplateExpression{}, false
	}
	return TemplateExpression{Node: n}, true
}

// TemplateHead wraps a TemplateHead node.
type TemplateHead struct{ Node }

// IsTemplateHead reports whether the node is a TemplateHead.
func (n Node) IsTemplateHead() bool { return ast.IsTemplateHead(n.node) }

// AsTemplateHead downcasts the node, or returns false.
func (n Node) AsTemplateHead() (TemplateHead, bool) {
	n.check()
	if !n.IsTemplateHead() {
		return TemplateHead{}, false
	}
	return TemplateHead{Node: n}, true
}

// TemplateLiteralTypeNode wraps a TemplateLiteralTypeNode node.
type TemplateLiteralTypeNode struct{ Node }

// IsTemplateLiteralTypeNode reports whether the node is a TemplateLiteralTypeNode.
func (n Node) IsTemplateLiteralTypeNode() bool { return ast.IsTemplateLiteralTypeNode(n.node) }

// AsTemplateLiteralTypeNode downcasts the node, or returns false.
func (n Node) AsTemplateLiteralTypeNode() (TemplateLiteralTypeNode, bool) {
	n.check()
	if !n.IsTemplateLiteralTypeNode() {
		return TemplateLiteralTypeNode{}, false
	}
	return TemplateLiteralTypeNode{Node: n}, true
}

// TemplateLiteralTypeSpan wraps a TemplateLiteralTypeSpan node.
type TemplateLiteralTypeSpan struct{ Node }

// IsTemplateLiteralTypeSpan reports whether the node is a TemplateLiteralTypeSpan.
func (n Node) IsTemplateLiteralTypeSpan() bool { return ast.IsTemplateLiteralTypeSpan(n.node) }

// AsTemplateLiteralTypeSpan downcasts the node, or returns false.
func (n Node) AsTemplateLiteralTypeSpan() (TemplateLiteralTypeSpan, bool) {
	n.check()
	if !n.IsTemplateLiteralTypeSpan() {
		return TemplateLiteralTypeSpan{}, false
	}
	return TemplateLiteralTypeSpan{Node: n}, true
}

// TemplateMiddle wraps a TemplateMiddle node.
type TemplateMiddle struct{ Node }

// IsTemplateMiddle reports whether the node is a TemplateMiddle.
func (n Node) IsTemplateMiddle() bool { return ast.IsTemplateMiddle(n.node) }

// AsTemplateMiddle downcasts the node, or returns false.
func (n Node) AsTemplateMiddle() (TemplateMiddle, bool) {
	n.check()
	if !n.IsTemplateMiddle() {
		return TemplateMiddle{}, false
	}
	return TemplateMiddle{Node: n}, true
}

// TemplateSpan wraps a TemplateSpan node.
type TemplateSpan struct{ Node }

// IsTemplateSpan reports whether the node is a TemplateSpan.
func (n Node) IsTemplateSpan() bool { return ast.IsTemplateSpan(n.node) }

// AsTemplateSpan downcasts the node, or returns false.
func (n Node) AsTemplateSpan() (TemplateSpan, bool) {
	n.check()
	if !n.IsTemplateSpan() {
		return TemplateSpan{}, false
	}
	return TemplateSpan{Node: n}, true
}

// TemplateTail wraps a TemplateTail node.
type TemplateTail struct{ Node }

// IsTemplateTail reports whether the node is a TemplateTail.
func (n Node) IsTemplateTail() bool { return ast.IsTemplateTail(n.node) }

// AsTemplateTail downcasts the node, or returns false.
func (n Node) AsTemplateTail() (TemplateTail, bool) {
	n.check()
	if !n.IsTemplateTail() {
		return TemplateTail{}, false
	}
	return TemplateTail{Node: n}, true
}

// ThisTypeNode wraps a ThisTypeNode node.
type ThisTypeNode struct{ Node }

// IsThisTypeNode reports whether the node is a ThisTypeNode.
func (n Node) IsThisTypeNode() bool { return ast.IsThisTypeNode(n.node) }

// AsThisTypeNode downcasts the node, or returns false.
func (n Node) AsThisTypeNode() (ThisTypeNode, bool) {
	n.check()
	if !n.IsThisTypeNode() {
		return ThisTypeNode{}, false
	}
	return ThisTypeNode{Node: n}, true
}

// ThrowStatement wraps a ThrowStatement node.
type ThrowStatement struct{ Node }

// IsThrowStatement reports whether the node is a ThrowStatement.
func (n Node) IsThrowStatement() bool { return ast.IsThrowStatement(n.node) }

// AsThrowStatement downcasts the node, or returns false.
func (n Node) AsThrowStatement() (ThrowStatement, bool) {
	n.check()
	if !n.IsThrowStatement() {
		return ThrowStatement{}, false
	}
	return ThrowStatement{Node: n}, true
}

// TryStatement wraps a TryStatement node.
type TryStatement struct{ Node }

// IsTryStatement reports whether the node is a TryStatement.
func (n Node) IsTryStatement() bool { return ast.IsTryStatement(n.node) }

// AsTryStatement downcasts the node, or returns false.
func (n Node) AsTryStatement() (TryStatement, bool) {
	n.check()
	if !n.IsTryStatement() {
		return TryStatement{}, false
	}
	return TryStatement{Node: n}, true
}

// TupleTypeNode wraps a TupleTypeNode node.
type TupleTypeNode struct{ Node }

// IsTupleTypeNode reports whether the node is a TupleTypeNode.
func (n Node) IsTupleTypeNode() bool { return ast.IsTupleTypeNode(n.node) }

// AsTupleTypeNode downcasts the node, or returns false.
func (n Node) AsTupleTypeNode() (TupleTypeNode, bool) {
	n.check()
	if !n.IsTupleTypeNode() {
		return TupleTypeNode{}, false
	}
	return TupleTypeNode{Node: n}, true
}

// TypeAssertion wraps a TypeAssertion node.
type TypeAssertion struct{ Node }

// IsTypeAssertion reports whether the node is a TypeAssertion.
func (n Node) IsTypeAssertion() bool { return ast.IsTypeAssertion(n.node) }

// AsTypeAssertion downcasts the node, or returns false.
func (n Node) AsTypeAssertion() (TypeAssertion, bool) {
	n.check()
	if !n.IsTypeAssertion() {
		return TypeAssertion{}, false
	}
	return TypeAssertion{Node: n}, true
}

// TypeLiteralNode wraps a TypeLiteralNode node.
type TypeLiteralNode struct{ Node }

// IsTypeLiteralNode reports whether the node is a TypeLiteralNode.
func (n Node) IsTypeLiteralNode() bool { return ast.IsTypeLiteralNode(n.node) }

// AsTypeLiteralNode downcasts the node, or returns false.
func (n Node) AsTypeLiteralNode() (TypeLiteralNode, bool) {
	n.check()
	if !n.IsTypeLiteralNode() {
		return TypeLiteralNode{}, false
	}
	return TypeLiteralNode{Node: n}, true
}

// TypeOfExpression wraps a TypeOfExpression node.
type TypeOfExpression struct{ Node }

// IsTypeOfExpression reports whether the node is a TypeOfExpression.
func (n Node) IsTypeOfExpression() bool { return ast.IsTypeOfExpression(n.node) }

// AsTypeOfExpression downcasts the node, or returns false.
func (n Node) AsTypeOfExpression() (TypeOfExpression, bool) {
	n.check()
	if !n.IsTypeOfExpression() {
		return TypeOfExpression{}, false
	}
	return TypeOfExpression{Node: n}, true
}

// TypeOperatorNode wraps a TypeOperatorNode node.
type TypeOperatorNode struct{ Node }

// IsTypeOperatorNode reports whether the node is a TypeOperatorNode.
func (n Node) IsTypeOperatorNode() bool { return ast.IsTypeOperatorNode(n.node) }

// AsTypeOperatorNode downcasts the node, or returns false.
func (n Node) AsTypeOperatorNode() (TypeOperatorNode, bool) {
	n.check()
	if !n.IsTypeOperatorNode() {
		return TypeOperatorNode{}, false
	}
	return TypeOperatorNode{Node: n}, true
}

// TypeParameterDeclaration wraps a TypeParameterDeclaration node.
type TypeParameterDeclaration struct{ Node }

// IsTypeParameterDeclaration reports whether the node is a TypeParameterDeclaration.
func (n Node) IsTypeParameterDeclaration() bool { return ast.IsTypeParameterDeclaration(n.node) }

// AsTypeParameterDeclaration downcasts the node, or returns false.
func (n Node) AsTypeParameterDeclaration() (TypeParameterDeclaration, bool) {
	n.check()
	if !n.IsTypeParameterDeclaration() {
		return TypeParameterDeclaration{}, false
	}
	return TypeParameterDeclaration{Node: n}, true
}

// TypePredicateNode wraps a TypePredicateNode node.
type TypePredicateNode struct{ Node }

// IsTypePredicateNode reports whether the node is a TypePredicateNode.
func (n Node) IsTypePredicateNode() bool { return ast.IsTypePredicateNode(n.node) }

// AsTypePredicateNode downcasts the node, or returns false.
func (n Node) AsTypePredicateNode() (TypePredicateNode, bool) {
	n.check()
	if !n.IsTypePredicateNode() {
		return TypePredicateNode{}, false
	}
	return TypePredicateNode{Node: n}, true
}

// TypeQueryNode wraps a TypeQueryNode node.
type TypeQueryNode struct{ Node }

// IsTypeQueryNode reports whether the node is a TypeQueryNode.
func (n Node) IsTypeQueryNode() bool { return ast.IsTypeQueryNode(n.node) }

// AsTypeQueryNode downcasts the node, or returns false.
func (n Node) AsTypeQueryNode() (TypeQueryNode, bool) {
	n.check()
	if !n.IsTypeQueryNode() {
		return TypeQueryNode{}, false
	}
	return TypeQueryNode{Node: n}, true
}

// TypeReferenceNode wraps a TypeReferenceNode node.
type TypeReferenceNode struct{ Node }

// IsTypeReferenceNode reports whether the node is a TypeReferenceNode.
func (n Node) IsTypeReferenceNode() bool { return ast.IsTypeReferenceNode(n.node) }

// AsTypeReferenceNode downcasts the node, or returns false.
func (n Node) AsTypeReferenceNode() (TypeReferenceNode, bool) {
	n.check()
	if !n.IsTypeReferenceNode() {
		return TypeReferenceNode{}, false
	}
	return TypeReferenceNode{Node: n}, true
}

// UnionTypeNode wraps a UnionTypeNode node.
type UnionTypeNode struct{ Node }

// IsUnionTypeNode reports whether the node is a UnionTypeNode.
func (n Node) IsUnionTypeNode() bool { return ast.IsUnionTypeNode(n.node) }

// AsUnionTypeNode downcasts the node, or returns false.
func (n Node) AsUnionTypeNode() (UnionTypeNode, bool) {
	n.check()
	if !n.IsUnionTypeNode() {
		return UnionTypeNode{}, false
	}
	return UnionTypeNode{Node: n}, true
}

// VariableDeclarationList wraps a VariableDeclarationList node.
type VariableDeclarationList struct{ Node }

// IsVariableDeclarationList reports whether the node is a VariableDeclarationList.
func (n Node) IsVariableDeclarationList() bool { return ast.IsVariableDeclarationList(n.node) }

// AsVariableDeclarationList downcasts the node, or returns false.
func (n Node) AsVariableDeclarationList() (VariableDeclarationList, bool) {
	n.check()
	if !n.IsVariableDeclarationList() {
		return VariableDeclarationList{}, false
	}
	return VariableDeclarationList{Node: n}, true
}

// VoidExpression wraps a VoidExpression node.
type VoidExpression struct{ Node }

// IsVoidExpression reports whether the node is a VoidExpression.
func (n Node) IsVoidExpression() bool { return ast.IsVoidExpression(n.node) }

// AsVoidExpression downcasts the node, or returns false.
func (n Node) AsVoidExpression() (VoidExpression, bool) {
	n.check()
	if !n.IsVoidExpression() {
		return VoidExpression{}, false
	}
	return VoidExpression{Node: n}, true
}

// WhileStatement wraps a WhileStatement node.
type WhileStatement struct{ Node }

// IsWhileStatement reports whether the node is a WhileStatement.
func (n Node) IsWhileStatement() bool { return ast.IsWhileStatement(n.node) }

// AsWhileStatement downcasts the node, or returns false.
func (n Node) AsWhileStatement() (WhileStatement, bool) {
	n.check()
	if !n.IsWhileStatement() {
		return WhileStatement{}, false
	}
	return WhileStatement{Node: n}, true
}

// WithStatement wraps a WithStatement node.
type WithStatement struct{ Node }

// IsWithStatement reports whether the node is a WithStatement.
func (n Node) IsWithStatement() bool { return ast.IsWithStatement(n.node) }

// AsWithStatement downcasts the node, or returns false.
func (n Node) AsWithStatement() (WithStatement, bool) {
	n.check()
	if !n.IsWithStatement() {
		return WithStatement{}, false
	}
	return WithStatement{Node: n}, true
}

// YieldExpression wraps a YieldExpression node.
type YieldExpression struct{ Node }

// IsYieldExpression reports whether the node is a YieldExpression.
func (n Node) IsYieldExpression() bool { return ast.IsYieldExpression(n.node) }

// AsYieldExpression downcasts the node, or returns false.
func (n Node) AsYieldExpression() (YieldExpression, bool) {
	n.check()
	if !n.IsYieldExpression() {
		return YieldExpression{}, false
	}
	return YieldExpression{Node: n}, true
}
